version: '3.2'

services:
  ds:
    # image: sasonline/django-db-services
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: /home/uweb/.pyenv/versions/uweb/bin/python manage.py runserver 0.0.0.0:8000
#    command: /home/uweb/.pyenv/versions/uweb/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 docroot.wsgi
    volumes:
     -  type: bind
        source: .
        target: /usr/src/app
    ports:
     - "8000:8000"
    environment:
     - TEST=Testing
     - DEBUG=True
