# Generated by Django 3.0.7 on 2020-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='connection_name',
            field=models.CharField(choices=[('default', 'default'), ('publications', 'publications'), ('web_cache', 'web_cache'), ('events', 'events'), ('web', 'web'), ('enterprise_data', 'enterprise_data'), ('eva', 'eva')], max_length=255),
        ),
    ]
