# Generated by Django 3.0.8 on 2020-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0003_auto_20200630_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='connection_name',
            field=models.CharField(choices=[('default', 'default'), ('web_cache', 'web_cache'), ('enterprise_data', 'enterprise_data'), ('eva', 'eva'), ('events', 'events')], max_length=255),
        ),
    ]
