# Generated by Django 3.0.8 on 2021-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0005_auto_20200903_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='log_filter_field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='log_filter_field_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='log_level_override',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Debug'), (20, 'Info')], null=True),
        ),
    ]
