# Generated by Django 3.0.8 on 2021-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_app', '0006_endpoint_logging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ['path']},
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='log_level_override',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Debug'), (20, 'Info'), (30, 'Warning')], null=True),
        ),
    ]
